@ stdcall sem_open (str long long long)
@ stdcall sem_post (ptr)
@ stdcall sem_wait (ptr)
@ stdcall sem_trywait (ptr)
@ stdcall sem_timedwait (ptr ptr)
@ stdcall sem_unlink (str)
@ stdcall sem_close (ptr)
@ stdcall get_product_info ()
@ stdcall get_version_info ()
